version: "2"
services:
  javabiblio:
    container_name: javabiblio
    restart: always
    build: .
    mem_limit: 512m
    mem_reservation: 128M
    ports:
      - "8081:8080"
#     - "9991:9990"
    networks:
      - linkDb
    environment:
      - JAVA_OPTS=-server -Xms256m -Xmx256m -XX:MetaspaceSize=96M -XX:MaxMetaspaceSize=256m -XX:MaxMetaspaceSize=256m -Djava.net.preferIPv4Stack=true -Djboss.modules.system.pkgs=org.jboss.byteman -Djava.awt.headless=true-Djava.net.preferIPv4Stack=true
  dbBiblio:
    image: "akoller/low-memory-mysql"
#    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: java@java.java
      MYSQL_DATABASE: java
      MYSQL_USER: java
      MYSQL_PASSWORD: java
    volumes:
#      - ./workdir/db/init/:/docker-entrypoint-initdb.d/
      - ./workdir/databiblio/:/var/lib/mysql/
      - ./javathis.sql:/docker-entrypoint-initdb.d/schema.sql:ro
    networks:
      - linkDb
  dbWallet:
    image: "akoller/low-memory-mysql"
#    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ewallet@ewallet.ewallet
      MYSQL_DATABASE: ewallet
      MYSQL_USER: ewallet
      MYSQL_PASSWORD: ewallet
    volumes:
#      - ./workdir/db/init/:/docker-entrypoint-initdb.d/
      - ./workdir/datawallet/:/var/lib/mysql/
      - ./ewallet.sql:/docker-entrypoint-initdb.d/schema.sql:ro
    networks:
      - linkDb
  dbCorsi:
    image: "akoller/low-memory-mysql"
#    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: corsi@corsi.corsi
      MYSQL_DATABASE: corsi
      MYSQL_USER: corsi
      MYSQL_PASSWORD: corsi
    volumes:
#      - ./workdir/db/init/:/docker-entrypoint-initdb.d/
      - ./workdir/dataCorsi/:/var/lib/mysql/
      - ./corsi.sql:/docker-entrypoint-initdb.d/schema.sql:ro
    networks:
      - linkDb


networks:
  linkDb:      
