
version: "2"
services:
  javabiblio:
    container_name: javabiblio
    restart: always
    build: .
    ports:
      - "8081:8080"
    networks:
      - linkDb
  dbMY:
    image: "mysql"
#    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: java@java.java
      MYSQL_DATABASE: java
      MYSQL_USER: java
      MYSQL_PASSWORD: java
    volumes:
#      - ./workdir/db/init/:/docker-entrypoint-initdb.d/
      - ./workdir/db/data/:/var/lib/mysql/
      - ./javathis.sql:/docker-entrypoint-initdb.d/schema.sql:ro
    networks:
      - linkDb
  dbWallet:
    image: "mysql"
#    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ewallet@ewallet.ewallet
      MYSQL_DATABASE: ewallet
      MYSQL_USER: ewallet
      MYSQL_PASSWORD: ewallet
    volumes:
#      - ./workdir/db/init/:/docker-entrypoint-initdb.d/
      - ./workdir/db/data2/:/var/lib/mysql/
      - ./ewallet.sql:/docker-entrypoint-initdb.d/schema.sql:ro
    networks:
      - linkDb


networks:
  linkDb:      
